language: node_js

node_js:
  - '6'

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: /home/travis/build/nieheyong/vue-tvideo/dist
  on:
    branch: master
