language: node_js

node_js:
  - '6'

install:
  - npm install

script:
  - ls
  - npm run build
  - ls

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
